### ISSUE TITLE
Working together.

### ISSUE THREAD

**Issue by jeddy3** [morishitter/csscs#3]
Hello,

I'm one of the co-authors of [stylelint](https://github.com/stylelint/stylelint). It's an postcss-based linter and code checker for CSS, and I think we're trying to solve the same problem. Perhaps we can work together?

We've written 88 rules so far:
https://github.com/stylelint/stylelint/blob/master/docs/rules.md

And here's a list of the what rules we think are left to do:
https://github.com/stylelint/stylelint/issues/1

We've tried to make the linter totally unopinionated, so you can configure it to your liking.

It's also pluggable, so can easily add your own rules (for example, if you wish to support a different syntax).

We're also [discussing adding auto correcting](https://github.com/stylelint/stylelint/issues/330), but I just noticed that you've already made substantial headway towards this problem with [cssfmt](https://github.com/morishitter/cssfmt).

Perhaps there's some way we can work together? Even if it's just informing users of their choices. For example, we could suggest using stylelint for linting (particularly useful for catching subtle coding errors like [overriding shorthand properties](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-no-shorthand-property-overrides/README.md) and the like) and suggest using cssfmt for auto-correcting the formatting (particularly useful with your editor plugins like atom-cssfmt).

What do you think?

**Comment by msaktype** [comment]
Hi, Rechard.

I wrote comment in [this issue](https://github.com/stylelint/stylelint/issues/330).
Why do you create issue in CSSCS? :D

**Comment by jeddy3** [comment]
Ooops, my bad. I misread the discussion in [this thread](https://github.com/morishitter/cssfmt/issues/4), and I didn't realised you had discontinued working on csssc in favour of cssfmt. I'll close this issue now :)
